services:
  - type: web
    name: shawed-pos-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000
      - path: /index.html
        name: Cache-Control
        value: public, max-age=0
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
